// actions types

export const LOAD_DATA = 'LOAD_DATA';
export const LOGIN_USER = 'LOGIN_USER';
export const LOAD_NOTIFICATIONS_DONE = 'LOAD_NOTIFICATIONS_DONE';
export const LOAD_STATISTICS_DONE = 'LOAD_STATISTICS_DONE';
export const LOGOUT_USER = 'LOGOUT_USER';
export const LOAD_USERS_DONE = 'LOAD_USERS_DONE';
export const UPDATE_USER_DONE = 'UPDATE_USER_DONE';
export const LOAD_EMAIL_SETTINGS_DONE = 'LOAD_EMAIL_SETTINGS_DONE';
export const LOAD_EXCEPTION_TYPES_DONE = 'LOAD_EXCEPTION_TYPES_DONE';
export const UPDATE_SETTINGS = 'UPDATE_SETTINGS';
export const LOAD_SLA_SETTINGS_DONE = 'LOAD_SLA_SETTINGS_DONE';
export const LOAD_QUERIES_DONE = 'LOAD_QUERIES_DONE';
export const LOAD_COUNTRIES_DONE = 'LOAD_COUNTRIES_DONE';
export const LOAD_CURRENCIES_DONE = 'LOAD_CURRENCIES_DONE';
export const LOAD_QUERY_DONE = 'LOAD_QUERY_DONE';
export const UPDATE_QUERIES_DONE = 'UPDATE_QUERIES_DONE';
export const IMPORT_QUERIES_DONE = 'IMPORT_QUERIES_DONE';
export const IMPORT_QUERIES_FAILED = 'IMPORT_QUERIES_FAILED';
export const IMPORT_QUERIES_START = 'IMPORT_QUERIES_START';
export const IMPORT_QUERIES_CANCEL = 'IMPORT_QUERIES_CANCEL';
export const IMPORT_QUERIES_PROGRESS = 'IMPORT_QUERIES_PROGRESS';
export const LOADING_START = 'LOADING_START';
export const LOADING_END = 'LOADING_END';
export const SHOW_MESSAGE = 'SHOW_MESSAGE';
export const HIDE_MESSAGE = 'HIDE_MESSAGE';